#!/bin/bash

~/.local/share/ohmydebn/bin/ohmydebn-headline "tte rain" "Installing new apps if unnecessary"
sudo DEBIAN_FRONTEND=noninteractive apt -y install alacritty \
  bat \
  bibata-cursor-theme \
  binutils \
  btop \
  cava \
  chromium \
  curl \
  eza \
  ffmpeg \
  fzf \
  galculator \
  gcc \
  gcolor3 \
  gir1.2-gtk4layershell-1.0 \
  git \
  gimp \
  golang \
  gum \
  gvfs-backends \
  htop \
  imagemagick \
  iperf3 \
  jq \
  keepassxc \
  lazygit \
  libadwaita-1-dev \
  libgtk-4-dev \
  libnotify-bin \
  lshw \
  neovim \
  openvpn \
  pdftk-java \
  pipx \
  pkg-config \
  python-is-python3 \
  ripgrep \
  ristretto \
  rofi \
  screenfetch \
  shellcheck \
  starship \
  systemd-timesyncd \
  ufw \
  vim \
  wget \
  xdotool \
  xournalpp \
  yaru-theme-gtk \
  yaru-theme-icon \
  yq \
  zip \
  zoxide \
  zsh \
  zsh-autosuggestions \
  zsh-syntax-highlighting
